import torch
import pandas as pd
import ast
from   pathlib import Path
from   datetime import datetime

from   model.config  import ModelConfig
from   model.globals import DATAPATH, HAND_GESTURE_CFG
from   model.model   import cnn_model, QuantConv2d

def get_hardware_weights(fused_layer: QuantConv2d, previous_act_scale: float = 1.0):
    '''Extracts the folded integer weights and biases directly from the QAT layer.
    
    Applies multi-bit activation scale compensation:
    y = W * (x_hw * act_scale) + b  →  (W * act_scale) * x_hw + b
    '''

    # 1. Recreate the exact BN fold that happened during training
    bn_scale = fused_layer.bn_weight / torch.sqrt(fused_layer.running_var + fused_layer.eps)
    folded_w = fused_layer.weight * bn_scale.view(-1, 1, 1, 1)
    folded_b = fused_layer.bn_bias - (fused_layer.running_mean * bn_scale)

    # Factor in the scale of the activations coming into this layer!
    folded_w = folded_w * previous_act_scale

    # 2. Retrieve the target bits directly from the layer
    target_bits = int(fused_layer._weight_bits)
    bias_bits = getattr(fused_layer, '_bias_bits', 8)

    # 3. Quantize to hardware integers
    qmin = -(2 ** (target_bits - 1))
    qmax = (2 ** (target_bits - 1)) - 1

    max_abs = folded_w.abs().max()
    w_scale = max_abs / qmax if max_abs > 0 else 1.0

    q_weights = torch.round(folded_w / w_scale)
    q_weights = torch.clip(q_weights, qmin, qmax)

    hw_bias = torch.round(folded_b / w_scale)

    # Safety: clamp biases to hardware bit-width
    b_max_val = 2**(bias_bits - 1) - 1
    b_min_val = -2**(bias_bits - 1)

    if (hw_bias > b_max_val).any() or (hw_bias < b_min_val).any():
        print(f"  [WARNING] Bias saturating! Max={hw_bias.abs().max().item():.0f}, Limit={b_max_val}")
        hw_bias = torch.clamp(hw_bias, b_min_val, b_max_val)

    return q_weights, hw_bias, float(w_scale)

def export_model_to_csv(model_path: Path, config: ModelConfig, output_csv: Path):
    '''Loads the trained model, extracts the folded and quantized weights for
    each layer, and saves them to a CSV file for hardware implementation.'''
    from model.quantize import QuantizeActivation
    device = "cpu"

    model = cnn_model(config=config).to(device)
    state = torch.load(model_path, map_location=device, weights_only=True)
    model.load_state_dict(state, strict=True)
    model.eval()

    all_hardware_data = []
    current_act_scale = 1.0 # Input pixels are binarized {0, 1} or normalized, start at 1.0

    print("Exporting Fused QAT layers to hardware CSV with scale propagation...")

    # We must iterate through all modules to track activation scales correctly
    # Features followed by Classifier
    all_modules = list(model.features.children()) + list(model.classifier.children())

    for module in all_modules:
        if isinstance(module, QuantConv2d):
            name = f"Layer_{len(all_hardware_data)}"
            weight_bits = module._weight_bits
            bias_bits   = module._bias_bits
            print(f"  Processing {name} ({module.__class__.__name__}) with incoming scale {current_act_scale:.6f}...")
            
            # Extract compensated weights
            w_int_tensor, b_hw, w_scale = get_hardware_weights(module, current_act_scale)

            # Convert to numpy
            w_int = w_int_tensor.to(torch.int32).cpu().numpy()
            b_int = b_hw.to(torch.int32).cpu().numpy()

            all_hardware_data.append({
                "layer_name": name,
                "weight_scale": w_scale,
                "weights_shape": str(tuple(w_int.shape)),
                "weight_bits" : weight_bits,
                "weights_flat": w_int.flatten().tolist(),
                "bias_bits" : bias_bits,
                "bias_flat": b_int.flatten().tolist(),
            })
        
        elif isinstance(module, QuantizeActivation):
            if module.bits == 1:
                # 1-bit activation in PyTorch is {-1, 1}.
                # In hardware it is {0, 1}. 
                # The effective scale remains 1.0 because the weights/inputs
                # are handled by XNOR logic which inherently maps {0, 1} back to {-1, 1}.
                current_act_scale = 1.0
            else:
                qmax = (2 ** (module.bits - 1)) - 1
                if module.clip_val is not None:
                    clip = float(module.clip_val.abs().item())
                    current_act_scale = clip / qmax
                    print(f"  Detected Activation Scaling: {current_act_scale:.6f} (clip={clip:.3f}, qmax={qmax})")
                else:
                    current_act_scale = 1.0
                    print(f"  Detected Activation Scaling: {current_act_scale:.6f} (Fixed Scale 1.0)")

    df = pd.DataFrame(all_hardware_data)
    df.to_csv(output_csv, index=False)
    print(f"\nHardware export complete! Saved to {output_csv}")

def export_csv_to_sv(csv_path, sv_path):
    '''Loads the CSV generated by export_model_to_csv and generates the SystemVerilog
    Header File containing packed weights and biases for hardware injection.
    '''
    date = datetime.now().strftime("%B %d, %Y %I:%M %p")
    sv_lines = [
        "// Auto-generated hardware parameters",
        f"// Date: {date}\n"
    ]
    
    # Force columns to be strings to avoid Pandas guessing types (like Timedelta)
    df = pd.read_csv(csv_path, dtype={"layer_name": str, "weight_scale": str, 
                                      "weights_shape": str, "weight_bits" : int, 
                                      "weights_flat": str, "bias_bits" : int, 
                                      "bias_flat": str})
    
    # Iterate through csv rows
    layer_num = 0
    for row in df.itertuples():
        layer_name = str(row.layer_name)
        w_bits = int(str(row.weight_bits))
        b_bits = int(str(row.bias_bits))

        # 1. Pack Weights into a single large bit-vector
        weights = ast.literal_eval(str(row.weights_flat))
        packed_w = 0
        for i, val in enumerate(weights):
            # Mask to bit-width to handle negative numbers correctly in hex
            masked_val = int(str(val)) & ((1 << w_bits) - 1)
            packed_w |= (masked_val << (i * w_bits))
        
        # 2. Pack Biases into a single large bit-vector
        biases = ast.literal_eval(str(row.bias_flat))
        packed_b = 0
        for i, val in enumerate(biases):
            masked_val = int(str(val)) & ((1 << b_bits) - 1)
            packed_b |= (masked_val << (i * b_bits))

        w_total_bits = len(weights) * w_bits
        b_total_bits = len(biases) * b_bits
        
        # Format as Verilog hex literals (e.g. 160'hABC...)
        max_digits = max(len(str(w_total_bits-1)), len(str(b_total_bits-1)))
        sv_lines.append(f"localparam logic signed [{w_total_bits-1:>{max_digits}}:0] LAYER_{layer_num}_WEIGHTS = {w_total_bits}'h{packed_w:x};")
        sv_lines.append(f"localparam logic signed [{b_total_bits-1:>{max_digits}}:0] LAYER_{layer_num}_BIASES  = {b_total_bits}'h{packed_b:x};")
        sv_lines.append("")
        layer_num += 1

    with open(sv_path, 'w') as f:
        f.write("\n".join(sv_lines))
    print(f"SystemVerilog export complete! Saved to {sv_path}")

if __name__ == "__main__":
    import sys
    # Default paths matching the training pipeline
    default_model = DATAPATH / "gesture_net_quantized.pth"
    default_csv   = DATAPATH / "hardware_weights.csv"
    default_sv    = DATAPATH / "hardware_weights.vh"

    model_in = Path(sys.argv[1]) if len(sys.argv) > 1 else default_model
    csv_out  = Path(sys.argv[2]) if len(sys.argv) > 2 else default_csv
    sv_out   = Path(sys.argv[3]) if len(sys.argv) > 3 else default_sv

    if not model_in.exists():
        print(f"Error: Model file not found at {model_in}")
        sys.exit(1)

    # 1. Refresh the CSV from the trained model
    export_model_to_csv(model_in, config=HAND_GESTURE_CFG, output_csv=csv_out)

    # 2. Generate the SystemVerilog header
    export_csv_to_sv(csv_out, sv_out)
        
    