import torch
import pandas as pd
import ast
from   pathlib import Path
from   datetime import datetime

from   model.config  import ModelConfig
from   model.globals import DATAPATH, HAND_GESTURE_CFG
from   model.model   import cnn_model, QuantConv2d

def get_hardware_weights(fused_layer: QuantConv2d):
    '''Extracts the folded integer weights and biases directly from the QAT layer,
       applying hardware-specific saturation constraints.'''

    # 1. Recreate the exact fold that happened during training
    bn_scale = fused_layer.bn_weight / torch.sqrt(fused_layer.running_var + fused_layer.eps)
    folded_w = fused_layer.weight * bn_scale.view(-1, 1, 1, 1)
    folded_b = fused_layer.bn_bias - (fused_layer.running_mean * bn_scale)

    # 2. Retrieve the target bits directly from the layer
    target_bits = int(fused_layer._weight_bits)
    # Fallback to 8 if you haven't updated the model class yet
    bias_bits = getattr(fused_layer, '_bias_bits', 8) 

    # 3. Quantize to extract the exact integer arrays the network learned
    qmin = -(2 ** (target_bits - 1))
    qmax = (2 ** (target_bits - 1)) - 1

    max_abs = folded_w.abs().max()
    w_scale = max_abs / qmax if max_abs > 0 else 1.0
    
    # Extract integer weights
    q_weights = torch.round(folded_w / w_scale)
    q_weights = torch.clip(q_weights, qmin, qmax)
    
    # Extract integer bias (using the exact same scale to maintain relative magnitude)
    hw_bias = torch.round(folded_b / w_scale)
    
    # --- SAFETY CHECK: Hardware Bias Saturation ---
    b_max_val = 2**(bias_bits - 1) - 1
    b_min_val = -2**(bias_bits - 1)
    
    if (hw_bias > b_max_val).any() or (hw_bias < b_min_val).any():
        print(f"  [WARNING] Bias saturating hardware limits! Max requested: {hw_bias.max().item():.0f}, Hardware Limit: {b_max_val}")
        # Clamp to physical hardware limits to ensure bit-accuracy in simulation
        hw_bias = torch.clamp(hw_bias, b_min_val, b_max_val)
    
    return q_weights, hw_bias, float(w_scale)

def export_model_to_csv(model_path: Path, config: ModelConfig, output_csv: Path):
    '''Loads the trained model, extracts the folded and quantized weights for
    each layer, and saves them to a CSV file for hardware implementation.'''
    device = "cpu"

    # Initialize model using the new config architecture
    model = cnn_model(config=config).to(device)
    state = torch.load(model_path, map_location=device, weights_only=True)
    model.load_state_dict(state, strict=True)
    model.eval()

    all_hardware_data = []

    print("Exporting Fused QAT layers to hardware CSV...")

    # Dynamically grab all Fused modules
    fused_layers = []
    for name, module in model.named_modules():
        if isinstance(module, QuantConv2d):
            fused_layers.append((name, module))

    for name, fused_layer in fused_layers:
        weight_bits = fused_layer._weight_bits
        bias_bits   = fused_layer._bias_bits
        print(f"  Processing {name} at {weight_bits}-bits...")
        
        # Extract folded weights, biases, and the scale
        w_int_tensor, b_hw, w_scale = get_hardware_weights(fused_layer)

        # Convert to numpy
        w_int = w_int_tensor.to(torch.int8).cpu().numpy()
        b_int = b_hw.to(torch.int32).cpu().numpy()

        all_hardware_data.append({
            "layer_name": name,
            "weight_scale": w_scale, # Saved for debugging / reference math
            "weights_shape": str(tuple(w_int.shape)),
            "weight_bits" : weight_bits,
            "weights_flat": w_int.flatten().tolist(),
            "bias_bits" : bias_bits,
            "bias_flat": b_int.flatten().tolist(),
        })

    df = pd.DataFrame(all_hardware_data)
    df.to_csv(output_csv, index=False)
    print(f"\nHardware export complete! Saved to {output_csv}")

def export_csv_to_sv(csv_path, sv_path):
    '''Loads the CSV generated by export_model_to_csv and generates the SystemVerilog
    Header File containing packed weights and biases for hardware injection.
    '''
    date = datetime.now().strftime("%B %d, %Y %I:%M %p")
    sv_lines = [
        "// Auto-generated hardware parameters",
        f"// Date: {date}\n"
    ]
    
    # Force columns to be strings to avoid Pandas guessing types (like Timedelta)
    df = pd.read_csv(csv_path, dtype={"layer_name": str, "weight_scale": str, 
                                      "weights_shape": str, "weight_bits" : int, 
                                      "weights_flat": str, "bias_bits" : int, 
                                      "bias_flat": str})
    
    # Iterate through csv rows
    layer_num = 0
    for row in df.itertuples():
        layer_name = str(row.layer_name)
        w_bits = int(str(row.weight_bits))
        b_bits = int(str(row.bias_bits))

        # 1. Pack Weights into a single large bit-vector
        weights = ast.literal_eval(str(row.weights_flat))
        packed_w = 0
        for i, val in enumerate(weights):
            # Mask to bit-width to handle negative numbers correctly in hex
            masked_val = int(str(val)) & ((1 << w_bits) - 1)
            packed_w |= (masked_val << (i * w_bits))
        
        # 2. Pack Biases into a single large bit-vector
        biases = ast.literal_eval(str(row.bias_flat))
        packed_b = 0
        for i, val in enumerate(biases):
            masked_val = int(str(val)) & ((1 << b_bits) - 1)
            packed_b |= (masked_val << (i * b_bits))

        w_total_bits = len(weights) * w_bits
        b_total_bits = len(biases) * b_bits
        
        # Format as Verilog hex literals (e.g. 160'hABC...)
        max_digits = max(len(str(w_total_bits-1)), len(str(b_total_bits-1)))
        sv_lines.append(f"localparam logic signed [{w_total_bits-1:>{max_digits}}:0] LAYER_{layer_num}_WEIGHTS = {w_total_bits}'h{packed_w:x};")
        sv_lines.append(f"localparam logic signed [{b_total_bits-1:>{max_digits}}:0] LAYER_{layer_num}_BIASES  = {b_total_bits}'h{packed_b:x};")
        sv_lines.append("")
        layer_num += 1

    with open(sv_path, 'w') as f:
        f.write("\n".join(sv_lines))
    print(f"SystemVerilog export complete! Saved to {sv_path}")

if __name__ == "__main__":
    import sys
    # Default paths matching the training pipeline
    default_model = DATAPATH / "gesture_net_quantized.pth"
    default_csv   = DATAPATH / "hardware_weights.csv"
    default_sv    = DATAPATH / "hardware_weights.vh"

    model_in = Path(sys.argv[1]) if len(sys.argv) > 1 else default_model
    csv_out  = Path(sys.argv[2]) if len(sys.argv) > 2 else default_csv
    sv_out   = Path(sys.argv[3]) if len(sys.argv) > 3 else default_sv

    if not model_in.exists():
        print(f"Error: Model file not found at {model_in}")
        sys.exit(1)

    # 1. Refresh the CSV from the trained model
    export_model_to_csv(model_in, config=HAND_GESTURE_CFG, output_csv=csv_out)

    # 2. Generate the SystemVerilog header
    export_csv_to_sv(csv_out, sv_out)
        
    