# render.py
# Bradley Manzo 2026

from datetime import datetime


def render_header(BusBits):
    date = datetime.now().strftime("%B %d, %Y %I:%M %p")
    lines = [
        "// cnn.sv",
        f"// Auto-generated by model.py on {date} - Do not edit directly!",
        "",
        "`timescale 1ns / 1ps",
        "module cnn (",
        "   input  [0:0] clk_i",
        "  ,input  [0:0] rst_i",
        "",
        "  ,input  [0:0] valid_i",
        "  ,input  [0:0] ready_i",
        "  ,input  [0:0] data_i",
        "",
        "  ,output [0:0] valid_o",
        "  ,output [0:0] ready_o",
        f"  ,output [{BusBits-1}:0] data_o", # FIXED: No longer [0:0]
        ");",
    ]

    return "\n".join(lines)

def render_wires(kernels):
    lines = []

    for layer in range(len(kernels)):
        for module in range(len(kernels[layer])):
            mode = "conv" if module == 0 else "pool"

            if not (layer == 0 and module == 0):
                lines.append(f"  wire [0:0] {mode}_{layer}_ready;")
                lines.append(f"  wire [0:0] {mode}_{layer}_valid;")
                lines.append(f"  wire [0:0] {mode}_{layer}_data;")

            is_last_module = module == len(kernels[layer]) - 1
            is_last_layer = layer == len(kernels) - 1

            if not (is_last_module and is_last_layer):
                lines.append("")

    lines.append("  wire [0:0] classifier_ready;")

    return "\n".join(lines)

def render_conv_layer(
    LineWidthPx,
    LineCountPx,
    InBits,
    OutBits,
    KernelWidth,
    WeightBits,
    InChannels,
    OutChannels,
    Stride,
    Weights,
    instance,
    num_instances,
    kernels,
    padding,
):
    # If at head of the first layer, connect to global input
    if instance == 0:
        valid_i = "valid_i"
        data_i  = "data_i"
        ready_o = "ready_o"
    # If the last layer did not have pooling, connect to the previous conv layer's output
    elif len(kernels[instance - 1]) == 1:  # If the last module in the previous layer is a conv, connect to that conv
        valid_i = f"conv_{instance - 1}_valid"
        data_i  = f"conv_{instance - 1}_data"
        ready_o = f"conv_{instance}_ready"
    # Otherwise, connect to the previous layer's pool
    else:
        valid_i = f"pool_{instance - 1}_valid"
        data_i  = f"pool_{instance - 1}_data"
        ready_o = f"conv_{instance}_ready"

    # If at tail of the last layer (right before classifier), drive internal wires
    if instance == num_instances - 1:
        ready_i = f"classifier_ready" # Classifier will drive this
        valid_o = f"conv_{instance}_valid" # Classifier will read this
        data_o  = f"conv_{instance}_data"  # Classifier will read this

    # If the current layer does not have pooling, connect to the next layer's input
    elif len(kernels[instance]) == 1:
        ready_i = f"conv_{instance + 1}_ready"
        valid_o = f"conv_{instance}_valid"
        data_o  = f"conv_{instance}_data"
        
    # Otherwise, connect to current layer's pool
    else:
        ready_i = f"pool_{instance}_ready"
        valid_o = f"conv_{instance}_valid"
        data_o  = f"conv_{instance}_data"
        
    lines = [
        "  conv_layer #(",
        f"     .LineWidthPx ({LineWidthPx})",
        f"    ,.LineCountPx ({LineCountPx})",
        f"    ,.InBits      ({InBits})",
        f"    ,.OutBits     ({OutBits})",
        f"    ,.KernelWidth ({KernelWidth})",
        f"    ,.WeightBits  ({WeightBits})",
        f"    ,.InChannels  ({InChannels})",
        f"    ,.OutChannels ({OutChannels})",
        f"    ,.Stride      ({Stride})",
        f"    ,.Weights     ({Weights})",
        f"    ,.Padding     ({padding})",
        f"  ) conv_layer_inst_{instance} (",
        "     .clk_i     (clk_i)",
        "    ,.rst_i     (rst_i)",
        "",
        f"    ,.ready_o  ({ready_o})",
        f"    ,.valid_i  ({valid_i})",
        f"    ,.data_i   ({data_i})",
        "",
        f"    ,.ready_i  ({ready_i})",
        f"    ,.valid_o  ({valid_o})",
        f"    ,.data_o   ({data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_pool_layer(
    LineWidthPx,
    LineCountPx,
    InBits,
    KernelWidth,
    InChannels,
    instance,
    PoolMode, # 0 for max pooling, 1 for average pooling
    num_instances,
    kernels,
):
    # Pool layers are always connected to the conv layer in the same block
    valid_i = f"conv_{instance}_valid"
    data_i  = f"conv_{instance}_data"

    # Pool layers are always followed by the next layer's conv block
    ready_i = f"conv_{instance + 1}_ready"

    # Pool layers are never at the immediate head or tail, so we don't need to
    # account for global input or output connections here.
    ready_o = f"pool_{instance}_ready"
    valid_o = f"pool_{instance}_valid"
    data_o  = f"pool_{instance}_data"

    lines = [
        "  pool_layer #(",
        f"     .LineWidthPx ({LineWidthPx})",
        f"    ,.LineCountPx ({LineCountPx})",
        f"    ,.InBits      ({InBits})",
        f"    ,.KernelWidth ({KernelWidth})",
        f"    ,.InChannels  ({InChannels})",
        f"    ,.PoolMode    ({PoolMode})", # PoolMode is fixed to 0 (max pooling) for now since we only support max pooling
        f"  ) pool_layer_inst_{instance} (",
        "     .clk_i    (clk_i)",
        "    ,.rst_i    (rst_i)",
        "",
        f"    ,.ready_o  ({ready_o})",
        f"    ,.valid_i  ({valid_i})",
        f"    ,.data_i   ({data_i})",
        "",
        f"    ,.ready_i  ({ready_i})",
        f"    ,.valid_o  ({valid_o})",
        f"    ,.data_o   ({data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_linear_layer(
    InBits,
    OutBits,
    WeightBits,
    BiasBits,
    InChannels,
    OutChannels,
    Weights,
    Biases,
    instance,
    num_instances,
    kernels,
):
    # If at head of the first layer, connect to global input
    if instance == 0:
        valid_i = "valid_i"
        data_i  = "data_i"
        ready_o = "ready_o"
    # If the last layer did not have pooling, connect to the previous conv/linear layer's output
    elif len(kernels[instance - 1]) == 1:
        valid_i = f"conv_{instance - 1}_valid"
        data_i  = f"conv_{instance - 1}_data"
        ready_o = f"conv_{instance}_ready"
    # Otherwise, connect to the previous layer's pool
    else:
        valid_i = f"pool_{instance - 1}_valid"
        data_i  = f"pool_{instance - 1}_data"
        ready_o = f"conv_{instance}_ready"

    # If at tail of the last layer (right before classifier), drive internal wires
    if instance == num_instances - 1:
        ready_i = "classifier_ready"
        valid_o = f"conv_{instance}_valid" # Classifier will read this
        data_o  = f"conv_{instance}_data"  # Classifier will read this

    # If the current layer does not have pooling, connect to the next layer's input
    elif len(kernels[instance]) == 1:
        ready_i = f"conv_{instance + 1}_ready"
        valid_o = f"conv_{instance}_valid"
        data_o  = f"conv_{instance}_data"
        
    # Otherwise, connect to current layer's pool
    else:
        ready_i = f"pool_{instance}_ready"
        valid_o = f"conv_{instance}_valid"
        data_o  = f"conv_{instance}_data"

    lines = [
        "  linear_layer #(",
        f"     .InBits      ({InBits})",
        f"    ,.OutBits     ({OutBits})",
        f"    ,.WeightBits  ({WeightBits})",
        f"    ,.BiasBits    ({BiasBits})",
        f"    ,.InChannels  ({InChannels})",
        f"    ,.OutChannels ({OutChannels})",
        f"    ,.Weights     ({Weights})",
        f"    ,.Biases      ({Biases})",
        f"  ) linear_layer_inst_{instance} (",
        "     .clk_i   (clk_i)",
        "    ,.rst_i   (rst_i)",
        "",
        f"    ,.ready_o  ({ready_o})",
        f"    ,.valid_i  ({valid_i})",
        f"    ,.data_i   ({data_i})",
        "",
        f"    ,.ready_i  ({ready_i})",
        f"    ,.valid_o  ({valid_o})",
        f"    ,.data_o   ({data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_classifier_layer(
    TermBits,
    TermCount,
    BusBits,
    InChannels,
    ClassCount,
    WeightBits,
    BiasBits,
    Weights,
    Biases,
    instance,
):
    # Classifier reads from the final linear/conv stage
    valid_i = f"conv_{instance - 1}_valid"
    data_i  = f"conv_{instance - 1}_data"
    
    # --- Classifier drives the dedicated ready wire ---
    ready_o = "classifier_ready"

    # Classifier drives the global output handshake
    ready_i = "ready_i"
    valid_o = "valid_o"
    
    # FIXED: Map the classifier's class_o to the top-level data_o port
    class_o = "data_o" 

    lines = [
        "  classifier_layer #(",
        f"     .TermBits   ({TermBits})",
        f"    ,.TermCount  ({TermCount})",
        f"    ,.BusBits    ({BusBits})",
        f"    ,.InChannels ({InChannels})",
        f"    ,.ClassCount ({ClassCount})",
        f"    ,.WeightBits ({WeightBits})",
        f"    ,.BiasBits   ({BiasBits})",
        f"    ,.Weights    ({Weights})",
        f"    ,.Biases     ({Biases})",
        f"  ) classifier_layer_inst_{instance} (",
        "     .clk_i   (clk_i)",
        "    ,.rst_i   (rst_i)",
        "",
        f"    ,.ready_o  ({ready_o})",
        f"    ,.valid_i  ({valid_i})",
        f"    ,.data_i   ({data_i})",
        "",
        f"    ,.valid_o  ({valid_o})",
        f"    ,.ready_i  ({ready_i})",
        f"    ,.class_o  ({class_o})",
        "  );\n",
    ]
    return "\n".join(lines)


def render_footer():
    lines = [
        "endmodule",
    ]
    return "\n".join(lines)