# render.py
# Bradley Manzo 2026

from datetime import datetime
from .config import ModelConfig, ConvConfig, PoolConfig, ClassifierConfig

def render_header(BusBits):
    date = datetime.now().strftime("%B %d, %Y %I:%M %p")
    lines = [
        "// cnn.sv",
        f"// Auto-generated by model.py on {date} - Do not edit directly!",
        "",
        "`timescale 1ns / 1ps",
        "module cnn #(",
        f"  parameter int unsigned BusBits = {BusBits}",
        ")  (",
        "   input  [0:0] clk_i",
        "  ,input  [0:0] rst_i",
        "",
        "  ,input  [0:0] valid_i",
        "  ,input  [0:0] ready_i",
        "  ,input  [0:0] data_i",
        "",
        "  ,output [0:0] valid_o",
        "  ,output [0:0] ready_o",
        "  ,output [BusBits-1:0] data_o", # FIXED: No longer [0:0]
        ");",
    ]

    return "\n".join(lines)

def render_wires(cfg: ModelConfig):
    lines = []

    for layer in cfg.layers:
        conv = layer.ConvLayer
        pool = layer.PoolLayer

        # Conv layer output wires
        if conv._ready_o != "ready_o":
            lines.append(f"  wire        [ 0:0]       {conv._ready_o};")
        if conv._valid_o != "valid_o":
            lines.append(f"  wire        [ 0:0]       {conv._valid_o};")
        if conv._data_o != "data_o":
            # Declare as 2D signed logic to match your architecture!
            if conv._out_ch is None or conv._out_bits is None:
                raise ValueError(f"Output channels or bits for layer {conv._layer_num} are not defined. Cannot render data wires.")
            lines.append(f"  wire signed [{conv._out_ch-1:2}:0][{conv._out_bits-1:2}:0] {conv._data_o};")

        # Pool layer output wires (if pool layer exists)
        if pool is not None:
            lines.append("") # Add a blank line between conv and pool wires for readability
            if pool._ready_o != "ready_o":
                lines.append(f"  wire        [ 0:0]       {pool._ready_o};")
            if pool._valid_o != "valid_o":
                lines.append(f"  wire        [ 0:0]       {pool._valid_o};")
            if pool._data_o != "data_o":
                lines.append(f"  wire signed [{pool._out_ch-1:2}:0][{pool._out_bits-1:2}:0] {pool._data_o};")

        lines.append("") # Add a blank line between blocks for readability

    # Classifier output wire (Since it is handled outside the loop)
    lines.append("  wire [0:0] classifier_ready;")

    return "\n".join(lines)

def render_conv_layer(cfg: ConvConfig):
   
    lines = [
        "  conv_layer #(",
        f"     .LineWidthPx ({cfg._input_dims.width})",
        f"    ,.LineCountPx ({cfg._input_dims.height})",
        f"    ,.InBits      ({cfg._in_bits})",
        f"    ,.OutBits     ({cfg._out_bits})",
        f"    ,.KernelWidth ({cfg._kernel_width})",
        f"    ,.WeightBits  ({cfg._q_schedule._q_min_bits})",
        f"    ,.InChannels  ({cfg._in_ch})",
        f"    ,.OutChannels ({cfg._out_ch})",
        f"    ,.Stride      ({cfg._stride})",
        f"    ,.Weights     (weights_{cfg._layer_num})",
        f"    ,.Padding     ({cfg._padding})",
        f"  ) conv_layer_inst_{cfg._layer_num} (",
        "     .clk_i     (clk_i)",
        "    ,.rst_i     (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.data_o   ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_pool_layer(cfg: PoolConfig):
    lines = [
        "  pool_layer #(",
        f"     .LineWidthPx ({cfg._input_dims.width})",
        f"    ,.LineCountPx ({cfg._input_dims.height})",
        f"    ,.InBits      ({cfg._in_bits})",
        f"    ,.KernelWidth ({cfg._kernel_width})",
        f"    ,.InChannels  ({cfg._in_ch})",
        f"    ,.PoolMode    ({cfg._mode})", # PoolMode is fixed to 0 (max pooling) for now since we only support max pooling
        f"  ) pool_layer_inst_{cfg._layer_num} (",
        "     .clk_i    (clk_i)",
        "    ,.rst_i    (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.data_o   ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_classifier_layer(cfg: ClassifierConfig):
    lines = [
        "  classifier_layer #(",
        f"     .TermBits   ({cfg._in_bits})",
        f"    ,.TermCount  ({cfg._term_count})",
        f"    ,.BusBits    (BusBits)",
        f"    ,.InChannels ({cfg._in_ch})",
        f"    ,.ClassCount ({cfg._num_classes})",
        f"    ,.WeightBits ({cfg._q_schedule._q_min_bits})",
        f"    ,.BiasBits   (8)",
        f"    ,.Weights    (weights_{cfg._layer_num})",
        f"    ,.Biases     (biases_{cfg._layer_num})",
        f"  ) classifier_layer_inst_{cfg._layer_num} (",
        "     .clk_i   (clk_i)",
        "    ,.rst_i   (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.class_o  ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)


def render_footer():
    lines = [
        "endmodule",
    ]
    return "\n".join(lines)