// server_html.c
// Bradley Manzo 2026
#include <stddef.h>

const char INDEX_HTML[] =
"<!doctype html>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<style>\n"
"  body{margin:0;background:#111;display:flex;justify-content:center;align-items:center;height:100vh}\n"
"  #wrap{display:flex;flex-direction:column;align-items:center;gap:12px}\n"
"  #dbg{color:#9f9;font:12px/1.3 monospace;white-space:pre-wrap;max-width:96vw}\n"
"  canvas{image-rendering:pixelated;max-width:100vw;max-height:90vh;display:block}\n"
"  #dl{font:12px/1 monospace;padding:8px 10px;border:1px solid #333;"
"      background:#1a1a1a;color:#ddd;border-radius:6px;cursor:pointer}\n"
"  #dl:hover{background:#222}\n"
"</style>\n"
"<div id=\"wrap\">\n"
"  <canvas id=\"c\"></canvas>\n"
"  <button id=\"dl\" type=\"button\">Download PNG</button>\n"
"  <pre id=\"dbg\">boot...</pre>\n"
"</div>\n"
"<script>\n"
"(function(){\n"
"  var pngClickCount = 0;\n"
"  var canvas = document.getElementById('c');\n"
"  var dbg = document.getElementById('dbg');\n"
"  var ctx = canvas.getContext('2d', { alpha: false });\n"
"  ctx.imageSmoothingEnabled = false;\n"
"  var PALETTE = [[0,0,0],[255,255,255]];\n"
"  var DATA_START = 10;\n"
"  function hex2(x){ return x.toString(16).padStart(2,'0'); }\n"
"\n"
"  function ts(){\n"
"    var d = new Date();\n"
"    function pad(n){ return String(n).padStart(2,'0'); }\n"
"    return String(d.getFullYear())\n"
"      + pad(d.getMonth()+1)\n"
"      + pad(d.getDate())\n"
"      + '_' + pad(d.getHours())\n"
"      + pad(d.getMinutes())\n"
"      + pad(d.getSeconds());\n"
"  }\n"
"\n"
"  document.getElementById('dl').addEventListener('click', function(){\n"
"    if(!canvas.width || !canvas.height){\n"
"      dbg.textContent = 'ERR: canvas is empty';\n"
"      return;\n"
"    }\n"
"    pngClickCount++;\n"
"    canvas.toBlob(function(blob){\n"
"      if(!blob){ dbg.textContent = 'ERR: PNG export failed'; return; }\n"
"      var url = URL.createObjectURL(blob);\n"
"      var a = document.createElement('a');\n"
"      a.href = url;\n"
"      a.download = 'thumbs_up_' + pngClickCount + '.png';\n"
"      document.body.appendChild(a);\n"
"      a.click();\n"
"      a.remove();\n"
"      URL.revokeObjectURL(url);\n"
"    }, 'image/png');\n"
"  });\n"
"\n"
"  async function fetchAndDraw(){\n"
"    var resp = await fetch('/frame?' + Date.now(), { cache: 'no-store' });\n"
"    if(!resp.ok) throw new Error('Fetch failed: ' + resp.status);\n"
"    var buf = await resp.arrayBuffer();\n"
"    var view = new Uint8Array(buf);\n"
"    if(view.length < DATA_START + 2) throw new Error('Frame too short: ' + view.length);\n"
"\n"
"    if(view[0] !== 0xFF || view[1] !== 0x01 || view[8] !== 0xFF || view[9] !== 0x02){\n"
"      throw new Error('Header mismatch: ' + hex2(view[0])+' '+hex2(view[1])+' '+hex2(view[8])+' '+hex2(view[9]));\n"
"    }\n"
"\n"
"    var h = (view[2] << 8) | view[3];\n"
"    var w = (view[4] << 8) | view[5];\n"
"    var payloadLen = (view[6] << 8) | view[7];\n"
"    var need = DATA_START + payloadLen + 2;\n"
"    if(view.length < need){\n"
"      throw new Error('Frame truncated: need ' + need + ', got ' + view.length);\n"
"    }\n"
"\n"
"    dbg.textContent = 'ok w=' + w + ' h=' + h + ' payloadLen=' + payloadLen + ' total=' + view.length;\n"
"\n"
"    canvas.width = w; canvas.height = h;\n"
"    var imageData = ctx.createImageData(w, h);\n"
"    var out = imageData.data;\n"
"    var pixels = w * h;\n"
"\n"
"    var pixelIndex = 0;\n"
"    for(var i = 0; i < payloadLen && pixelIndex < pixels; i++){\n"
"      var b = view[DATA_START + i];\n"
"      for(var bit = 0; bit < 8 && pixelIndex < pixels; bit++){\n"
"        var color = (b >> bit) & 1; // LSB-first\n"
"        var RGB = PALETTE[color];\n"
"        var base = pixelIndex * 4;\n"
"        out[base+0] = RGB[0];\n"
"        out[base+1] = RGB[1];\n"
"        out[base+2] = RGB[2];\n"
"        out[base+3] = 255;\n"
"        pixelIndex++;\n"
"      }\n"
"    }\n"
"\n"
"    ctx.putImageData(imageData, 0, 0);\n"
"\n"
"    var vw = window.innerWidth;\n"
"    var vh = window.innerHeight;\n"
"    var scaleX = Math.floor(vw / w) || 1;\n"
"    var scaleY = Math.floor(vh / h) || 1;\n"
"    var scale = Math.max(1, Math.min(scaleX, scaleY));\n"
"    canvas.style.width = (w * scale) + 'px';\n"
"    canvas.style.height = (h * scale) + 'px';\n"
"  }\n"
"\n"
"  async function tick(){\n"
"    try{ await fetchAndDraw(); }\n"
"    catch(err){ dbg.textContent = 'ERR: ' + err.message; console.error(err); }\n"
"  }\n"
"\n"
"  tick();\n"
"  setInterval(tick, 1000);\n"
"})();\n"
"</script>\n";

const size_t INDEX_HTML_LEN = sizeof(INDEX_HTML) - 1;