# !/usr/bin/env python3
# nn.render.py
# Bradley Manzo 2026

from   datetime import datetime
from   pathlib  import Path
import re

from nn.config  import NNConfig, ConvConfig, PoolConfig, ClassifierConfig
from nn.globals import NN_CFG

def _rom_needs_hi(cfg) -> bool:
    '''True when a layer's ROM exceeds one SB_RAM40_4K tile (16 bits wide).'''
    if isinstance(cfg, ConvConfig):
        if cfg._dsp_count <= 0:
            return False
        effective_dsps = min(cfg._dsp_count, cfg._out_ch or 0)
        return effective_dsps * cfg._q_schedule._q_min_bits > 16
    elif isinstance(cfg, ClassifierConfig):
        if cfg._dsp_count <= 0:
            return False
        effective_dsps = min(cfg._dsp_count, cfg._num_classes or 0)
        return effective_dsps * cfg._q_schedule._q_min_bits > 16
    return False

def _lo_hex(i: int) -> str:
    return f"nn/data/roms/hex/layer_{i}_weights_lo.hex"

def _hi_hex(i: int) -> str:
    return f"nn/data/roms/hex/layer_{i}_weights_hi.hex"

def _std_hex(i: int) -> str:
    return f"nn/data/roms/hex/layer_{i}_weights.hex"

def render_header(cfg, num_layers: int = 1):
    '''Renders the header of the CNN SystemVerilog file.'''
    if isinstance(cfg, NNConfig):
        BusBits = cfg._bus_width
        layer_cfgs = [l.ConvLayer for l in cfg.layers]
    else:
        BusBits = cfg  # legacy: first arg is BusBits int
        layer_cfgs = []

    # Timestamp the file for traceability
    date = datetime.now().strftime("%B %d, %Y %I:%M %p")
    lines = [
        "// cnn.sv",
        f"// Auto-generated by render.py on {date} - Do not edit directly!",
        "",
        "`timescale 1ns / 1ps",
        "module cnn #(",
        f"  parameter int unsigned BusBits = {BusBits}",
    ]

    def _plain_params():
        for i in range(num_layers):
            if i < len(layer_cfgs):
                needs_hi = _rom_needs_hi(layer_cfgs[i])
            else:
                classifier_cfg = cfg.classifier_config if isinstance(cfg, NNConfig) else None
                needs_hi = _rom_needs_hi(classifier_cfg) if classifier_cfg is not None else False
            if needs_hi:
                yield f"  ,parameter              FileName_{i}    = \"{_lo_hex(i)}\""
                yield f"  ,parameter              FileName_{i}_hi = \"{_hi_hex(i)}\""
            else:
                yield f"  ,parameter              FileName_{i} = \"{_std_hex(i)}\""

    # Add FileName parameters for each layer to support ROM injection
    lines.extend(_plain_params())
    
    lines.extend([
        ")  (",
        "   input  [0:0] clk_i",
        "  ,input  [0:0] rst_i",
        "",
        "  ,input  [0:0] valid_i",
        "  ,output [0:0] ready_o",
        "  ,input logic signed [0:0][0:0] data_i",
        "",
        "  ,output [0:0] valid_o",
        "  ,input  [0:0] ready_i",
        "  ,output logic signed [0:0][BusBits-1:0] data_o",
        ");",
        "",
        "  `ifdef SYNTHESIS",
        "    `include \"nn/data/hardware_weights.vh\"",
        "  `elsif COCOTB_SIM",
        "    `include \"injected_weights_0.vh\"",
        "  `else",
        "    `error \"Please define SYNTHESIS or COCOTB_SIM\"",
        "  `endif",
        "",
    ])

    return "\n".join(lines)

def render_wires(cfg: NNConfig):
    '''Renders the wire declarations for the CNN SystemVerilog file.'''
    lines = []

    for layer in cfg.layers:
        conv = layer.ConvLayer
        pool = layer.PoolLayer

        # Conv layer output wires
        if conv._ready_o != "ready_o":
            lines.append(f"  wire              [ 0:0] {conv._ready_o};")
        if conv._valid_o != "valid_o":
            lines.append(f"  wire              [ 0:0] {conv._valid_o};")
        if conv._data_o  != "data_o":
            # Declare as 2D signed logic to match your architecture!
            if conv._out_ch is None or conv._out_bits is None:
                raise ValueError(f"Output channels or bits for layer {conv._layer_num} are not defined. Cannot render data wires.")
            lines.append(f"  wire signed [{conv._out_ch-1:2}:0][{conv._out_bits-1:2}:0] {conv._data_o};")

        # Pool layer output wires (if pool layer exists)
        if pool is not None:
            lines.append("") # Add a blank line between conv and pool wires for readability
            if pool._ready_o != "ready_o":
                lines.append(f"  wire              [ 0:0] {pool._ready_o};")
            if pool._valid_o != "valid_o":
                lines.append(f"  wire              [ 0:0] {pool._valid_o};")
            if pool._data_o  != "data_o":
                lines.append(f"  wire signed [{pool._out_ch-1:2}:0][{pool._out_bits-1:2}:0] {pool._data_o};")

        lines.append("") # Add a blank line between blocks for readability

    # Classifier output wire (Since it is handled outside the loop)
    lines.append("  wire              [ 0:0] classifier_ready;")

    return "\n".join(lines)

def render_conv_layer(cfg: ConvConfig, is_last_feature: bool = False):
    '''Renders a convolution layer within the CNN SystemVerilog file.'''
    lines = [
        "  conv_layer #(",
        f"     .LineWidthPx ({cfg._input_dims.width})",
        f"    ,.LineCountPx ({cfg._input_dims.height})",
        f"    ,.InBits      ({cfg._in_bits})",
        f"    ,.OutBits     ({cfg._out_bits})",
        f"    ,.KernelWidth ({cfg._kernel_width})",
        f"    ,.WeightBits  ({cfg._q_schedule._q_min_bits})",
        f"    ,.BiasBits    ({cfg._bias_bits})", # Bias bits are fixed to 8 for now since we haven't implemented quantized biases
        f"    ,.InChannels  ({cfg._in_ch})",
        f"    ,.OutChannels ({cfg._out_ch})",
        f"    ,.Stride      ({cfg._stride})",
        f"    ,.Weights     (LAYER_{cfg._layer_num}_WEIGHTS)",
        f"    ,.Biases      (LAYER_{cfg._layer_num}_BIASES)",
        f"    ,.Padding     ({cfg._padding})",
        f"    ,.DSPCount    ({cfg._dsp_count})",
        f"    ,.Unsigned    ({1 if cfg._in_bits > 2 else 0})",
    ]
    if is_last_feature:
        lines.append("    ,.ShiftBits   (CLASSIFIER_SHIFT)")
    elif cfg._out_bits > 2:
        lines.append(f"    ,.ShiftBits   (LAYER_{cfg._layer_num}_SHIFT)")
    lines.append(f"    ,.FileName    (FileName_{cfg._layer_num})")
    if _rom_needs_hi(cfg):
        lines.append(f"    ,.FileName_hi (FileName_{cfg._layer_num}_hi)")
    lines += [
        f"  ) conv_layer_inst_{cfg._layer_num} (",
        "     .clk_i     (clk_i)",
        "    ,.rst_i     (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.data_o   ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_pool_layer(cfg: PoolConfig):
    '''Renders a pooling layer within the CNN SystemVerilog file.'''
    # in_bits > 2 means input comes from a gen_learned_shift conv (ReLU + right-shift = unsigned)
    unsigned = 1 if cfg._in_bits > 2 else 0
    lines = [
        "  pool_layer #(",
        f"     .LineWidthPx ({cfg._input_dims.width})",
        f"    ,.LineCountPx ({cfg._input_dims.height})",
        f"    ,.InBits      ({cfg._in_bits})",
        f"    ,.OutBits     ({cfg._out_bits})",
        f"    ,.KernelWidth ({cfg._kernel_width})",
        f"    ,.InChannels  ({cfg._in_ch})",
        f"    ,.PoolMode    ({cfg._mode})",
        f"    ,.Unsigned    ({unsigned})",
        f"  ) pool_layer_inst_{cfg._layer_num} (",
        "     .clk_i    (clk_i)",
        "    ,.rst_i    (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.data_o   ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_classifier_layer(cfg: ClassifierConfig):
    '''Renders the classifier layer within the CNN SystemVerilog file.'''
    lines = [
        "  classifier_layer #(",
        f"     .TermBits   ({cfg._in_bits})",
        f"    ,.TermCount  ({cfg._term_count})",
        f"    ,.BusBits    (BusBits)",
        f"    ,.InChannels ({cfg._in_ch})",
        f"    ,.ClassCount ({cfg._num_classes})",
        f"    ,.WeightBits ({cfg._q_schedule._q_min_bits})",
        f"    ,.BiasBits   ({cfg._bias_bits})", # Bias bits are fixed to 8 for now since we haven't implemented quantized biases
        f"    ,.Weights    (LAYER_{cfg._layer_num}_WEIGHTS)",
        f"    ,.Biases     (LAYER_{cfg._layer_num}_BIASES)",
        f"    ,.DSPCount   ({cfg._dsp_count})",
        f"    ,.FileName   (FileName_{cfg._layer_num})",
    ]
    if _rom_needs_hi(cfg):
        lines.append(f"    ,.FileName_hi (FileName_{cfg._layer_num}_hi)")
    lines += [
        f"  ) classifier_layer_inst_{cfg._layer_num} (",
        "     .clk_i   (clk_i)",
        "    ,.rst_i   (rst_i)",
        "",
        f"    ,.ready_o  ({cfg._ready_o})",
        f"    ,.valid_i  ({cfg._valid_i})",
        f"    ,.data_i   ({cfg._data_i})",
        "",
        f"    ,.valid_o  ({cfg._valid_o})",
        f"    ,.ready_i  ({cfg._ready_i})",
        f"    ,.class_o  ({cfg._data_o})",
        "  );\n",
    ]
    return "\n".join(lines)

def render_footer():
    '''Renders the footer of the CNN SystemVerilog file.'''
    lines = [
        "endmodule",
    ]
    return "\n".join(lines)

def _build_filename_rows(cfg: NNConfig):
    '''Yields (layer_idx, needs_hi) for every layer including the classifier.'''
    layer_cfgs = [l.ConvLayer for l in cfg.layers]
    for i in range(len(layer_cfgs) + 1):
        lcfg = layer_cfgs[i] if i < len(layer_cfgs) else cfg.classifier_config
        yield i, _rom_needs_hi(lcfg)


def patch_uart_cnn_sv(cfg: NNConfig, path: Path) -> None:
    '''Keep FileName parameter declarations and cnn forwarding in uart_cnn.sv in sync with cnn.sv.'''
    decl_lines, fwd_lines = [], []
    for i, needs_hi in _build_filename_rows(cfg):
        if needs_hi:
            decl_lines += [f'  ,parameter FileName_{i}    = "{_lo_hex(i)}"',
                           f'  ,parameter FileName_{i}_hi = "{_hi_hex(i)}"']
            fwd_lines  += [f'    ,.FileName_{i}    (FileName_{i})',
                           f'    ,.FileName_{i}_hi (FileName_{i}_hi)']
        else:
            decl_lines.append(f'  ,parameter FileName_{i}    = "{_std_hex(i)}"')
            fwd_lines.append( f'    ,.FileName_{i}    (FileName_{i})')

    text = path.read_text(encoding="utf-8")
    text = re.sub(r'(?:  ,parameter FileName_\S+ *= *"[^"]*"\n)+',
                  '\n'.join(decl_lines) + '\n', text)
    text = re.sub(r'(?:    ,\.FileName_\S+ *\(FileName_[A-Za-z0-9_]+\)\n)+',
                  '\n'.join(fwd_lines) + '\n', text)
    path.write_text(text, encoding="utf-8")


def patch_top_sv(cfg: NNConfig, path: Path) -> None:
    '''Keep FileName arguments in the uart_cnn instantiation in top.sv in sync with cnn.sv.'''
    arg_lines = []
    for i, needs_hi in _build_filename_rows(cfg):
        if needs_hi:
            arg_lines += [f'    ,.FileName_{i}    ("{_lo_hex(i)}")',
                          f'    ,.FileName_{i}_hi ("{_hi_hex(i)}")']
        else:
            arg_lines.append(f'    ,.FileName_{i}    ("{_std_hex(i)}")')

    text = path.read_text(encoding="utf-8")
    text = re.sub(r'(?:    ,\.FileName_\S+ *\("[^"]*"\)\n)+',
                  '\n'.join(arg_lines) + '\n', text)
    path.write_text(text, encoding="utf-8")


def render_verilog(cfg: NNConfig) -> None:
    '''Render the CNN architecture to a SystemVerilog file for hardware implementation.'''
    repo_root = Path(__file__).resolve().parents[1]
    out_file = repo_root / "rtl" / "blocks" / "cnn.sv"

    with open(out_file, "w", encoding="utf-8") as f:
        print(render_header(cfg, num_layers=len(cfg.layers) + 1), file=f)
        print(render_wires(cfg), file=f)
        print("", file=f)

        # Render Feature Layers
        num_feature_layers = len(cfg.layers)
        for i, layer_cfg in enumerate(cfg.layers):
            print(render_conv_layer(layer_cfg.ConvLayer, is_last_feature=(i == num_feature_layers - 1)), file=f)
            if layer_cfg.PoolLayer is not None:
                print(render_pool_layer(layer_cfg.PoolLayer), file=f)

        # Render Classifier
        print(render_classifier_layer(cfg.classifier_config), file=f)

        print(render_footer(), file=f)

    patch_uart_cnn_sv(cfg, repo_root / "rtl" / "top" / "uart_cnn.sv")
    patch_top_sv(cfg, repo_root / "rtl" / "top" / "top.sv")
    print("Run make bitstream ESP=1 ?")

if __name__ == "__main__":
   render_verilog(NN_CFG)