// cnn.sv
// Auto-generated by render.py on May 20, 2026 06:51 PM - Do not edit directly!

`timescale 1ns / 1ps
module cnn #(
  parameter int unsigned BusBits = 8
  ,parameter              FileName_0 = "nn/data/roms/hex/layer_0_weights.hex"
  ,parameter              FileName_1    = "nn/data/roms/hex/layer_1_weights_lo.hex"
  ,parameter              FileName_1_hi = "nn/data/roms/hex/layer_1_weights_hi.hex"
  ,parameter              FileName_2    = "nn/data/roms/hex/layer_2_weights_lo.hex"
  ,parameter              FileName_2_hi = "nn/data/roms/hex/layer_2_weights_hi.hex"
  ,parameter              FileName_3 = "nn/data/roms/hex/layer_3_weights.hex"
)  (
   input  [0:0] clk_i
  ,input  [0:0] rst_i

  ,input  [0:0] valid_i
  ,output [0:0] ready_o
  ,input logic signed [0:0][0:0] data_i

  ,output [0:0] valid_o
  ,input  [0:0] ready_i
  ,output logic signed [0:0][BusBits-1:0] data_o
);

  `ifdef SYNTHESIS
    `include "nn/data/hardware_weights.vh"
  `elsif COCOTB_SIM
    `include "injected_weights_0.vh"
  `else
    `error "Please define SYNTHESIS or COCOTB_SIM"
  `endif

  wire              [ 0:0] conv_0_valid;
  wire signed [ 3:0][ 2:0] conv_0_data;

  wire              [ 0:0] pool_0_ready;
  wire              [ 0:0] pool_0_valid;
  wire signed [ 3:0][ 2:0] pool_0_data;

  wire              [ 0:0] conv_1_ready;
  wire              [ 0:0] conv_1_valid;
  wire signed [ 8:0][ 2:0] conv_1_data;

  wire              [ 0:0] pool_1_ready;
  wire              [ 0:0] pool_1_valid;
  wire signed [ 8:0][ 2:0] pool_1_data;

  wire              [ 0:0] conv_2_ready;
  wire              [ 0:0] conv_2_valid;
  wire signed [11:0][ 3:0] conv_2_data;

  wire              [ 0:0] classifier_ready;

  conv_layer #(
     .LineWidthPx (28)
    ,.LineCountPx (28)
    ,.InBits      (1)
    ,.OutBits     (3)
    ,.KernelWidth (3)
    ,.WeightBits  (3)
    ,.BiasBits    (8)
    ,.InChannels  (1)
    ,.OutChannels (4)
    ,.Stride      (1)
    ,.Weights     (LAYER_0_WEIGHTS)
    ,.Biases      (LAYER_0_BIASES)
    ,.Padding     (1)
    ,.DSPCount    (0)
    ,.Unsigned    (0)
    ,.ShiftBits   (LAYER_0_SHIFT)
    ,.FileName    (FileName_0)
  ) conv_layer_inst_0 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (ready_o)
    ,.valid_i  (valid_i)
    ,.data_i   (data_i)

    ,.ready_i  (pool_0_ready)
    ,.valid_o  (conv_0_valid)
    ,.data_o   (conv_0_data)
  );

  pool_layer #(
     .LineWidthPx (28)
    ,.LineCountPx (28)
    ,.InBits      (3)
    ,.OutBits     (3)
    ,.KernelWidth (2)
    ,.InChannels  (4)
    ,.PoolMode    (0)
    ,.Unsigned    (1)
  ) pool_layer_inst_0 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_0_ready)
    ,.valid_i  (conv_0_valid)
    ,.data_i   (conv_0_data)

    ,.ready_i  (conv_1_ready)
    ,.valid_o  (pool_0_valid)
    ,.data_o   (pool_0_data)
  );

  conv_layer #(
     .LineWidthPx (14)
    ,.LineCountPx (14)
    ,.InBits      (3)
    ,.OutBits     (3)
    ,.KernelWidth (3)
    ,.WeightBits  (8)
    ,.BiasBits    (16)
    ,.InChannels  (4)
    ,.OutChannels (9)
    ,.Stride      (1)
    ,.Weights     (LAYER_1_WEIGHTS)
    ,.Biases      (LAYER_1_BIASES)
    ,.Padding     (1)
    ,.DSPCount    (3)
    ,.Unsigned    (1)
    ,.ShiftBits   (LAYER_1_SHIFT)
    ,.FileName    (FileName_1)
    ,.FileName_hi (FileName_1_hi)
  ) conv_layer_inst_1 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (conv_1_ready)
    ,.valid_i  (pool_0_valid)
    ,.data_i   (pool_0_data)

    ,.ready_i  (pool_1_ready)
    ,.valid_o  (conv_1_valid)
    ,.data_o   (conv_1_data)
  );

  pool_layer #(
     .LineWidthPx (14)
    ,.LineCountPx (14)
    ,.InBits      (3)
    ,.OutBits     (3)
    ,.KernelWidth (2)
    ,.InChannels  (9)
    ,.PoolMode    (0)
    ,.Unsigned    (1)
  ) pool_layer_inst_1 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_1_ready)
    ,.valid_i  (conv_1_valid)
    ,.data_i   (conv_1_data)

    ,.ready_i  (conv_2_ready)
    ,.valid_o  (pool_1_valid)
    ,.data_o   (pool_1_data)
  );

  conv_layer #(
     .LineWidthPx (7)
    ,.LineCountPx (7)
    ,.InBits      (3)
    ,.OutBits     (4)
    ,.KernelWidth (3)
    ,.WeightBits  (8)
    ,.BiasBits    (16)
    ,.InChannels  (9)
    ,.OutChannels (12)
    ,.Stride      (1)
    ,.Weights     (LAYER_2_WEIGHTS)
    ,.Biases      (LAYER_2_BIASES)
    ,.Padding     (1)
    ,.DSPCount    (4)
    ,.Unsigned    (1)
    ,.ShiftBits   (CLASSIFIER_SHIFT)
    ,.FileName    (FileName_2)
    ,.FileName_hi (FileName_2_hi)
  ) conv_layer_inst_2 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (conv_2_ready)
    ,.valid_i  (pool_1_valid)
    ,.data_i   (pool_1_data)

    ,.ready_i  (classifier_ready)
    ,.valid_o  (conv_2_valid)
    ,.data_o   (conv_2_data)
  );

  classifier_layer #(
     .TermBits   (4)
    ,.TermCount  (49)
    ,.BusBits    (BusBits)
    ,.InChannels (12)
    ,.ClassCount (10)
    ,.WeightBits (8)
    ,.BiasBits   (32)
    ,.Weights    (LAYER_3_WEIGHTS)
    ,.Biases     (LAYER_3_BIASES)
    ,.DSPCount   (1)
    ,.FileName   (FileName_3)
  ) classifier_layer_inst_3 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (classifier_ready)
    ,.valid_i  (conv_2_valid)
    ,.data_i   (conv_2_data)

    ,.valid_o  (valid_o)
    ,.ready_i  (ready_i)
    ,.class_o  (data_o)
  );

endmodule
