// cnn.sv
// Auto-generated by model.py on April 19, 2026 10:28 PM - Do not edit directly!

`timescale 1ns / 1ps
module cnn (
   input  [0:0] clk_i
  ,input  [0:0] rst_i

  ,input  [0:0] valid_i
  ,input  [0:0] ready_i
  ,input  [0:0] data_i

  ,output [0:0] valid_o
  ,output [0:0] ready_o
  ,output [0:0] data_o
);

  wire [0:0] pool_0_ready;
  wire [0:0] pool_0_valid;
  wire [0:0] pool_0_data;

  wire [0:0] conv_1_ready;
  wire [0:0] conv_1_valid;
  wire [0:0] conv_1_data;

  wire [0:0] pool_1_ready;
  wire [0:0] pool_1_valid;
  wire [0:0] pool_1_data;

  wire [0:0] conv_2_ready;
  wire [0:0] conv_2_valid;
  wire [0:0] conv_2_data;

  wire [0:0] pool_2_ready;
  wire [0:0] pool_2_valid;
  wire [0:0] pool_2_data;

  wire [0:0] conv_3_ready;
  wire [0:0] conv_3_valid;
  wire [0:0] conv_3_data;

  wire [0:0] conv_4_ready;
  wire [0:0] conv_4_valid;
  wire [0:0] conv_4_data;

  conv_layer #(
     .LineWidthPx (320)
    ,.LineCountPx (240)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (1)
    ,.OutChannels (8)
    ,.Stride      (1)
    ,.Weights     (weights_0)
  ) conv_layer_inst_0 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (ready_o)
    ,.valid_i  (valid_i)
    ,.data_i   (data_i)

    ,.ready_i  (pool_0_ready)
    ,.valid_o  (conv_0_valid)
    ,.data_o   (conv_0_data)
  );

  pool_layer #(
     .LineWidthPx (318)
    ,.LineCountPx (238)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (8)
  ) pool_layer_inst_0 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_0_ready)
    ,.valid_i  (conv_0_valid)
    ,.data_i   (conv_0_data)

    ,.ready_i  (conv_1_ready)
    ,.valid_o  (pool_0_valid)
    ,.data_o   (pool_0_data)
  );

  conv_layer #(
     .LineWidthPx (159)
    ,.LineCountPx (119)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (8)
    ,.OutChannels (16)
    ,.Stride      (1)
    ,.Weights     (weights_1)
  ) conv_layer_inst_1 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (conv_1_ready)
    ,.valid_i  (pool_0_valid)
    ,.data_i   (pool_0_data)

    ,.ready_i  (pool_1_ready)
    ,.valid_o  (conv_1_valid)
    ,.data_o   (conv_1_data)
  );

  pool_layer #(
     .LineWidthPx (157)
    ,.LineCountPx (117)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (16)
  ) pool_layer_inst_1 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_1_ready)
    ,.valid_i  (conv_1_valid)
    ,.data_i   (conv_1_data)

    ,.ready_i  (conv_2_ready)
    ,.valid_o  (pool_1_valid)
    ,.data_o   (pool_1_data)
  );

  conv_layer #(
     .LineWidthPx (78)
    ,.LineCountPx (58)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (16)
    ,.OutChannels (24)
    ,.Stride      (1)
    ,.Weights     (weights_2)
  ) conv_layer_inst_2 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (conv_2_ready)
    ,.valid_i  (pool_1_valid)
    ,.data_i   (pool_1_data)

    ,.ready_i  (pool_2_ready)
    ,.valid_o  (conv_2_valid)
    ,.data_o   (conv_2_data)
  );

  pool_layer #(
     .LineWidthPx (76)
    ,.LineCountPx (56)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (24)
  ) pool_layer_inst_2 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_2_ready)
    ,.valid_i  (conv_2_valid)
    ,.data_i   (conv_2_data)

    ,.ready_i  (conv_3_ready)
    ,.valid_o  (pool_2_valid)
    ,.data_o   (pool_2_data)
  );

  conv_layer #(
     .LineWidthPx (38)
    ,.LineCountPx (28)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (24)
    ,.OutChannels (32)
    ,.Stride      (1)
    ,.Weights     (weights_3)
  ) conv_layer_inst_3 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (conv_3_ready)
    ,.valid_i  (pool_2_valid)
    ,.data_i   (pool_2_data)

    ,.ready_i  (conv_4_ready)
    ,.valid_o  (conv_3_valid)
    ,.data_o   (conv_3_data)
  );

  conv_layer #(
     .LineWidthPx (36)
    ,.LineCountPx (26)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (1)
    ,.WeightBits  (8)
    ,.InChannels  (32)
    ,.OutChannels (10)
    ,.Stride      (1)
    ,.Weights     (weights_4)
  ) conv_layer_inst_4 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (conv_4_ready)
    ,.valid_i  (conv_3_valid)
    ,.data_i   (conv_3_data)

    ,.ready_i  (ready_i)
    ,.valid_o  (valid_o)
    ,.data_o   (data_o)
  );

endmodule
