// cnn.sv
// Auto-generated by model.py on April 29, 2026 09:18 PM - Do not edit directly!

`timescale 1ns / 1ps
module cnn #(
  parameter int unsigned BusBits = 8
)  (
   input  [0:0] clk_i
  ,input  [0:0] rst_i

  ,input  [0:0] valid_i
  ,input  [0:0] ready_i
  ,input  [0:0] data_i

  ,output [0:0] valid_o
  ,output [0:0] ready_o
  ,output [BusBits-1:0] data_o
);
  wire        [ 0:0]       conv_0_valid;
  wire signed [ 7:0][ 0:0] conv_0_data;

  wire        [ 0:0]       pool_0_ready;
  wire        [ 0:0]       pool_0_valid;
  wire signed [ 7:0][ 0:0] pool_0_data;

  wire        [ 0:0]       conv_1_ready;
  wire        [ 0:0]       conv_1_valid;
  wire signed [15:0][ 0:0] conv_1_data;

  wire        [ 0:0]       pool_1_ready;
  wire        [ 0:0]       pool_1_valid;
  wire signed [15:0][ 0:0] pool_1_data;

  wire        [ 0:0]       conv_2_ready;
  wire        [ 0:0]       conv_2_valid;
  wire signed [23:0][ 0:0] conv_2_data;

  wire        [ 0:0]       pool_2_ready;
  wire        [ 0:0]       pool_2_valid;
  wire signed [23:0][ 0:0] pool_2_data;

  wire        [ 0:0]       conv_3_ready;
  wire        [ 0:0]       conv_3_valid;
  wire signed [31:0][12:0] conv_3_data;

  wire [0:0] classifier_ready;

  conv_layer #(
     .LineWidthPx (320)
    ,.LineCountPx (240)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (1)
    ,.OutChannels (8)
    ,.Stride      (1)
    ,.Weights     (weights_0)
    ,.Padding     (1)
  ) conv_layer_inst_0 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (ready_o)
    ,.valid_i  (valid_i)
    ,.data_i   (data_i)

    ,.ready_i  (pool_0_ready)
    ,.valid_o  (conv_0_valid)
    ,.data_o   (conv_0_data)
  );

  pool_layer #(
     .LineWidthPx (320)
    ,.LineCountPx (240)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (8)
    ,.PoolMode    (0)
  ) pool_layer_inst_0 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_0_ready)
    ,.valid_i  (conv_0_valid)
    ,.data_i   (conv_0_data)

    ,.ready_i  (conv_1_ready)
    ,.valid_o  (pool_0_valid)
    ,.data_o   (pool_0_data)
  );

  conv_layer #(
     .LineWidthPx (160)
    ,.LineCountPx (120)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (8)
    ,.OutChannels (16)
    ,.Stride      (1)
    ,.Weights     (weights_1)
    ,.Padding     (1)
  ) conv_layer_inst_1 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (conv_1_ready)
    ,.valid_i  (pool_0_valid)
    ,.data_i   (pool_0_data)

    ,.ready_i  (pool_1_ready)
    ,.valid_o  (conv_1_valid)
    ,.data_o   (conv_1_data)
  );

  pool_layer #(
     .LineWidthPx (160)
    ,.LineCountPx (120)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (16)
    ,.PoolMode    (0)
  ) pool_layer_inst_1 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_1_ready)
    ,.valid_i  (conv_1_valid)
    ,.data_i   (conv_1_data)

    ,.ready_i  (conv_2_ready)
    ,.valid_o  (pool_1_valid)
    ,.data_o   (pool_1_data)
  );

  conv_layer #(
     .LineWidthPx (80)
    ,.LineCountPx (60)
    ,.InBits      (1)
    ,.OutBits     (1)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (16)
    ,.OutChannels (24)
    ,.Stride      (1)
    ,.Weights     (weights_2)
    ,.Padding     (1)
  ) conv_layer_inst_2 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (conv_2_ready)
    ,.valid_i  (pool_1_valid)
    ,.data_i   (pool_1_data)

    ,.ready_i  (pool_2_ready)
    ,.valid_o  (conv_2_valid)
    ,.data_o   (conv_2_data)
  );

  pool_layer #(
     .LineWidthPx (80)
    ,.LineCountPx (60)
    ,.InBits      (1)
    ,.KernelWidth (2)
    ,.InChannels  (24)
    ,.PoolMode    (0)
  ) pool_layer_inst_2 (
     .clk_i    (clk_i)
    ,.rst_i    (rst_i)

    ,.ready_o  (pool_2_ready)
    ,.valid_i  (conv_2_valid)
    ,.data_i   (conv_2_data)

    ,.ready_i  (conv_3_ready)
    ,.valid_o  (pool_2_valid)
    ,.data_o   (pool_2_data)
  );

  conv_layer #(
     .LineWidthPx (40)
    ,.LineCountPx (30)
    ,.InBits      (1)
    ,.OutBits     (13)
    ,.KernelWidth (3)
    ,.WeightBits  (4)
    ,.InChannels  (24)
    ,.OutChannels (32)
    ,.Stride      (1)
    ,.Weights     (weights_3)
    ,.Padding     (1)
  ) conv_layer_inst_3 (
     .clk_i     (clk_i)
    ,.rst_i     (rst_i)

    ,.ready_o  (conv_3_ready)
    ,.valid_i  (pool_2_valid)
    ,.data_i   (pool_2_data)

    ,.ready_i  (classifier_ready)
    ,.valid_o  (conv_3_valid)
    ,.data_o   (conv_3_data)
  );

  classifier_layer #(
     .TermBits   (13)
    ,.TermCount  (1200)
    ,.BusBits    (BusBits)
    ,.InChannels (32)
    ,.ClassCount (10)
    ,.WeightBits (8)
    ,.BiasBits   (8)
    ,.Weights    (weights_4)
    ,.Biases     (biases_4)
  ) classifier_layer_inst_4 (
     .clk_i   (clk_i)
    ,.rst_i   (rst_i)

    ,.ready_o  (classifier_ready)
    ,.valid_i  (conv_3_valid)
    ,.data_i   (conv_3_data)

    ,.valid_o  (valid_o)
    ,.ready_i  (ready_i)
    ,.class_o  (data_o)
  );

endmodule
